#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("ProgrammingIdeas.Resource", IsApplication=true)]

namespace ProgrammingIdeas
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Animation
		{
			
			// aapt resource value: 0x7f050000
			public const int push_down_in = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int push_down_out = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int push_left_in = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int push_left_out = 2131034115;
			
			// aapt resource value: 0x7f050004
			public const int push_right_in = 2131034116;
			
			// aapt resource value: 0x7f050005
			public const int push_right_out = 2131034117;
			
			// aapt resource value: 0x7f050006
			public const int push_up_in = 2131034118;
			
			// aapt resource value: 0x7f050007
			public const int push_up_out = 2131034119;
			
			static Animation()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Animation()
			{
			}
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f0b0000
			public const int categories = 2131427328;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010004
			public const int cardBackgroundColor = 2130771972;
			
			// aapt resource value: 0x7f010005
			public const int cardCornerRadius = 2130771973;
			
			// aapt resource value: 0x7f010006
			public const int cardElevation = 2130771974;
			
			// aapt resource value: 0x7f010007
			public const int cardMaxElevation = 2130771975;
			
			// aapt resource value: 0x7f010009
			public const int cardPreventCornerOverlap = 2130771977;
			
			// aapt resource value: 0x7f010008
			public const int cardUseCompatPadding = 2130771976;
			
			// aapt resource value: 0x7f01000a
			public const int contentPadding = 2130771978;
			
			// aapt resource value: 0x7f01000e
			public const int contentPaddingBottom = 2130771982;
			
			// aapt resource value: 0x7f01000b
			public const int contentPaddingLeft = 2130771979;
			
			// aapt resource value: 0x7f01000c
			public const int contentPaddingRight = 2130771980;
			
			// aapt resource value: 0x7f01000d
			public const int contentPaddingTop = 2130771981;
			
			// aapt resource value: 0x7f010000
			public const int layoutManager = 2130771968;
			
			// aapt resource value: 0x7f010002
			public const int reverseLayout = 2130771970;
			
			// aapt resource value: 0x7f010001
			public const int spanCount = 2130771969;
			
			// aapt resource value: 0x7f010003
			public const int stackFromEnd = 2130771971;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f090007
			public const int accent = 2131296263;
			
			// aapt resource value: 0x7f090008
			public const int bgLight = 2131296264;
			
			// aapt resource value: 0x7f09000c
			public const int cardSubtitle = 2131296268;
			
			// aapt resource value: 0x7f090000
			public const int cardview_dark_background = 2131296256;
			
			// aapt resource value: 0x7f090001
			public const int cardview_light_background = 2131296257;
			
			// aapt resource value: 0x7f090002
			public const int cardview_shadow_end_color = 2131296258;
			
			// aapt resource value: 0x7f090003
			public const int cardview_shadow_start_color = 2131296259;
			
			// aapt resource value: 0x7f09000f
			public const int doneColor = 2131296271;
			
			// aapt resource value: 0x7f090012
			public const int highlight = 2131296274;
			
			// aapt resource value: 0x7f09000e
			public const int inProgressColor = 2131296270;
			
			// aapt resource value: 0x7f090004
			public const int primary = 2131296260;
			
			// aapt resource value: 0x7f090005
			public const int primaryDark = 2131296261;
			
			// aapt resource value: 0x7f090006
			public const int primaryLight = 2131296262;
			
			// aapt resource value: 0x7f090010
			public const int primary_pressed = 2131296272;
			
			// aapt resource value: 0x7f090011
			public const int ripple = 2131296273;
			
			// aapt resource value: 0x7f09000a
			public const int subtitleColor = 2131296266;
			
			// aapt resource value: 0x7f09000b
			public const int titleColor = 2131296267;
			
			// aapt resource value: 0x7f09000d
			public const int undecidedColor = 2131296269;
			
			// aapt resource value: 0x7f090009
			public const int windowBackground = 2131296265;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f060003
			public const int cardview_compat_inset_shadow = 2131099651;
			
			// aapt resource value: 0x7f060004
			public const int cardview_default_elevation = 2131099652;
			
			// aapt resource value: 0x7f060005
			public const int cardview_default_radius = 2131099653;
			
			// aapt resource value: 0x7f060007
			public const int itemProgressDimen = 2131099655;
			
			// aapt resource value: 0x7f060000
			public const int item_touch_helper_max_drag_scroll_per_frame = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int item_touch_helper_swipe_escape_max_velocity = 2131099649;
			
			// aapt resource value: 0x7f060002
			public const int item_touch_helper_swipe_escape_velocity = 2131099650;
			
			// aapt resource value: 0x7f060006
			public const int progressDimensions = 2131099654;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int circle = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int done = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int inprogress = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int roundBtn = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int submitBtn = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int submitRoundBtn = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int undecided = 2130837510;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070035
			public const int about = 2131165237;
			
			// aapt resource value: 0x7f07002a
			public const int authorTb = 2131165226;
			
			// aapt resource value: 0x7f07002f
			public const int bookmarkItem = 2131165231;
			
			// aapt resource value: 0x7f070004
			public const int bookmarkRecyclerView = 2131165188;
			
			// aapt resource value: 0x7f070032
			public const int bookmarks = 2131165234;
			
			// aapt resource value: 0x7f070002
			public const int bugsy = 2131165186;
			
			// aapt resource value: 0x7f070007
			public const int categoryIcon = 2131165191;
			
			// aapt resource value: 0x7f070008
			public const int categoryLbl = 2131165192;
			
			// aapt resource value: 0x7f070006
			public const int categoryRoot = 2131165190;
			
			// aapt resource value: 0x7f070036
			public const int changelog = 2131165238;
			
			// aapt resource value: 0x7f070009
			public const int completedLbl = 2131165193;
			
			// aapt resource value: 0x7f07000a
			public const int descriptionLbl = 2131165194;
			
			// aapt resource value: 0x7f070018
			public const int difficulty = 2131165208;
			
			// aapt resource value: 0x7f07001e
			public const int done = 2131165214;
			
			// aapt resource value: 0x7f07001f
			public const int doneText = 2131165215;
			
			// aapt resource value: 0x7f070013
			public const int editNote = 2131165203;
			
			// aapt resource value: 0x7f070001
			public const int fuckyouLinker = 2131165185;
			
			// aapt resource value: 0x7f07000b
			public const int ideaCard = 2131165195;
			
			// aapt resource value: 0x7f07002d
			public const int ideaDescription = 2131165229;
			
			// aapt resource value: 0x7f07001c
			public const int inProgress = 2131165212;
			
			// aapt resource value: 0x7f07001d
			public const int inprogressText = 2131165213;
			
			// aapt resource value: 0x7f07000d
			public const int itemDescription = 2131165197;
			
			// aapt resource value: 0x7f070019
			public const int itemId = 2131165209;
			
			// aapt resource value: 0x7f070014
			public const int itemRecyclerView = 2131165204;
			
			// aapt resource value: 0x7f07000c
			public const int itemTitle = 2131165196;
			
			// aapt resource value: 0x7f070000
			public const int item_touch_helper_previous_elevation = 2131165184;
			
			// aapt resource value: 0x7f070015
			public const int layoutRoot = 2131165205;
			
			// aapt resource value: 0x7f070023
			public const int newIdeaCategory = 2131165219;
			
			// aapt resource value: 0x7f070024
			public const int newIdeaContent = 2131165220;
			
			// aapt resource value: 0x7f070020
			public const int newIdeaRecyclerView = 2131165216;
			
			// aapt resource value: 0x7f070022
			public const int newIdeaTitle = 2131165218;
			
			// aapt resource value: 0x7f070034
			public const int newIdeas = 2131165236;
			
			// aapt resource value: 0x7f070021
			public const int newIdeasText = 2131165217;
			
			// aapt resource value: 0x7f070031
			public const int notes = 2131165233;
			
			// aapt resource value: 0x7f070026
			public const int notesActivitySwitcher = 2131165222;
			
			// aapt resource value: 0x7f07000e
			public const int notesCard = 2131165198;
			
			// aapt resource value: 0x7f070027
			public const int notesContent = 2131165223;
			
			// aapt resource value: 0x7f070028
			public const int notesEdit = 2131165224;
			
			// aapt resource value: 0x7f070029
			public const int notesEditBtn = 2131165225;
			
			// aapt resource value: 0x7f070012
			public const int notesInput = 2131165202;
			
			// aapt resource value: 0x7f070011
			public const int notesLbl = 2131165201;
			
			// aapt resource value: 0x7f070025
			public const int notesRecyclerView = 2131165221;
			
			// aapt resource value: 0x7f070010
			public const int notesSwitcher = 2131165200;
			
			// aapt resource value: 0x7f07000f
			public const int notesTitle = 2131165199;
			
			// aapt resource value: 0x7f070003
			public const int parent = 2131165187;
			
			// aapt resource value: 0x7f070017
			public const int progressState = 2131165207;
			
			// aapt resource value: 0x7f070005
			public const int recyclerView = 2131165189;
			
			// aapt resource value: 0x7f070030
			public const int shareItem = 2131165232;
			
			// aapt resource value: 0x7f07002c
			public const int spinner = 2131165228;
			
			// aapt resource value: 0x7f07002e
			public const int submitBtn = 2131165230;
			
			// aapt resource value: 0x7f070033
			public const int submitIdea = 2131165235;
			
			// aapt resource value: 0x7f07002b
			public const int submitTitle = 2131165227;
			
			// aapt resource value: 0x7f070016
			public const int title = 2131165206;
			
			// aapt resource value: 0x7f07001a
			public const int undecided = 2131165210;
			
			// aapt resource value: 0x7f07001b
			public const int undecidedText = 2131165211;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f040000
			public const int aboutactivity = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int bookmarksactivity = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int categoryactivity = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int categoryrow = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int ideadetailsactivity = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int idealistactivity = 2130968581;
			
			// aapt resource value: 0x7f040006
			public const int idealistrow = 2130968582;
			
			// aapt resource value: 0x7f040007
			public const int ideaprogressfragment = 2130968583;
			
			// aapt resource value: 0x7f040008
			public const int newideasfragment = 2130968584;
			
			// aapt resource value: 0x7f040009
			public const int newideasrow = 2130968585;
			
			// aapt resource value: 0x7f04000a
			public const int notesactivity = 2130968586;
			
			// aapt resource value: 0x7f04000b
			public const int notesrow = 2130968587;
			
			// aapt resource value: 0x7f04000c
			public const int submitideaactivity = 2130968588;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f0c0000
			public const int itemdetails_menu = 2131492864;
			
			// aapt resource value: 0x7f0c0001
			public const int menu_main = 2131492865;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f030000
			public const int cpu = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int database = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int enterprise = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int file = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int games = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int ic_bookmark_border_white_24dp = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int ic_bookmark_white_24dp = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int ic_edit_white_24dp = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int ic_mode_edit_white_24dp = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int ic_new_releases_white_24dp = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int ic_note_white_24dp = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int ic_share_white_24dp = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int Icon = 2130903052;
			
			// aapt resource value: 0x7f03000d
			public const int multimedia = 2130903053;
			
			// aapt resource value: 0x7f03000e
			public const int network = 2130903054;
			
			// aapt resource value: 0x7f03000f
			public const int numbers = 2130903055;
			
			// aapt resource value: 0x7f030010
			public const int text = 2130903056;
			
			// aapt resource value: 0x7f030011
			public const int web = 2130903057;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f0a001c
			public const int alansa_2016 = 2131361820;
			
			// aapt resource value: 0x7f0a0003
			public const int appNumber = 2131361795;
			
			// aapt resource value: 0x7f0a0002
			public const int appVersion = 2131361794;
			
			// aapt resource value: 0x7f0a0001
			public const int app_name = 2131361793;
			
			// aapt resource value: 0x7f0a000d
			public const int authorHint = 2131361805;
			
			// aapt resource value: 0x7f0a0025
			public const int author_name = 2131361829;
			
			// aapt resource value: 0x7f0a0009
			public const int bookmark = 2131361801;
			
			// aapt resource value: 0x7f0a001d
			public const int bug_reports = 2131361821;
			
			// aapt resource value: 0x7f0a0000
			public const int category = 2131361792;
			
			// aapt resource value: 0x7f0a000c
			public const int changelog = 2131361804;
			
			// aapt resource value: 0x7f0a0019
			public const int completed = 2131361817;
			
			// aapt resource value: 0x7f0a0014
			public const int completedText = 2131361812;
			
			// aapt resource value: 0x7f0a0007
			public const int description = 2131361799;
			
			// aapt resource value: 0x7f0a0006
			public const int difficulty = 2131361798;
			
			// aapt resource value: 0x7f0a0012
			public const int editNote = 2131361810;
			
			// aapt resource value: 0x7f0a0010
			public const int edit_text = 2131361808;
			
			// aapt resource value: 0x7f0a0024
			public const int enter_an_indepth_description_of_the_idea = 2131361828;
			
			// aapt resource value: 0x7f0a0026
			public const int enter_the_idea_s_title = 2131361830;
			
			// aapt resource value: 0x7f0a0027
			public const int enter_your_name = 2131361831;
			
			// aapt resource value: 0x7f0a000e
			public const int helpText = 2131361806;
			
			// aapt resource value: 0x7f0a001f
			public const int idea_bag_icon = 2131361823;
			
			// aapt resource value: 0x7f0a0020
			public const int idea_category = 2131361824;
			
			// aapt resource value: 0x7f0a0021
			public const int idea_contents = 2131361825;
			
			// aapt resource value: 0x7f0a0028
			public const int idea_description = 2131361832;
			
			// aapt resource value: 0x7f0a0029
			public const int idea_title = 2131361833;
			
			// aapt resource value: 0x7f0a001a
			public const int in_progress = 2131361818;
			
			// aapt resource value: 0x7f0a0015
			public const int in_progressText = 2131361813;
			
			// aapt resource value: 0x7f0a0005
			public const int itemId = 2131361797;
			
			// aapt resource value: 0x7f0a000a
			public const int loadingText = 2131361802;
			
			// aapt resource value: 0x7f0a0016
			public const int markProgressText = 2131361814;
			
			// aapt resource value: 0x7f0a0018
			public const int need_help_with_the_solution_to_this_idea = 2131361816;
			
			// aapt resource value: 0x7f0a0022
			public const int new_ideas_in_this_update = 2131361826;
			
			// aapt resource value: 0x7f0a0017
			public const int note = 2131361815;
			
			// aapt resource value: 0x7f0a0011
			public const int notesHint = 2131361809;
			
			// aapt resource value: 0x7f0a000f
			public const int notes_sample_content = 2131361807;
			
			// aapt resource value: 0x7f0a001e
			public const int overview = 2131361822;
			
			// aapt resource value: 0x7f0a000b
			public const int overviewText = 2131361803;
			
			// aapt resource value: 0x7f0a002b
			public const int select_the_idea_s_category = 2131361835;
			
			// aapt resource value: 0x7f0a0008
			public const int share = 2131361800;
			
			// aapt resource value: 0x7f0a002a
			public const int submit_idea = 2131361834;
			
			// aapt resource value: 0x7f0a0004
			public const int title = 2131361796;
			
			// aapt resource value: 0x7f0a001b
			public const int undecided = 2131361819;
			
			// aapt resource value: 0x7f0a0013
			public const int undecidedText = 2131361811;
			
			// aapt resource value: 0x7f0a0023
			public const int you_have_no_notes_yet = 2131361827;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f080001
			public const int Base_CardView = 2131230721;
			
			// aapt resource value: 0x7f080000
			public const int CardView = 2131230720;
			
			// aapt resource value: 0x7f080002
			public const int CardView_Dark = 2131230722;
			
			// aapt resource value: 0x7f080003
			public const int CardView_Light = 2131230723;
			
			// aapt resource value: 0x7f080006
			public const int MyActionBar = 2131230726;
			
			// aapt resource value: 0x7f080004
			public const int MyTheme = 2131230724;
			
			// aapt resource value: 0x7f080005
			public const int MyTheme_Base = 2131230725;
			
			// aapt resource value: 0x7f080007
			public const int SubmitTheme = 2131230727;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] CardView = new int[] {
					16843071,
					16843072,
					2130771972,
					2130771973,
					2130771974,
					2130771975,
					2130771976,
					2130771977,
					2130771978,
					2130771979,
					2130771980,
					2130771981,
					2130771982};
			
			// aapt resource value: 1
			public const int CardView_android_minHeight = 1;
			
			// aapt resource value: 0
			public const int CardView_android_minWidth = 0;
			
			// aapt resource value: 2
			public const int CardView_cardBackgroundColor = 2;
			
			// aapt resource value: 3
			public const int CardView_cardCornerRadius = 3;
			
			// aapt resource value: 4
			public const int CardView_cardElevation = 4;
			
			// aapt resource value: 5
			public const int CardView_cardMaxElevation = 5;
			
			// aapt resource value: 7
			public const int CardView_cardPreventCornerOverlap = 7;
			
			// aapt resource value: 6
			public const int CardView_cardUseCompatPadding = 6;
			
			// aapt resource value: 8
			public const int CardView_contentPadding = 8;
			
			// aapt resource value: 12
			public const int CardView_contentPaddingBottom = 12;
			
			// aapt resource value: 9
			public const int CardView_contentPaddingLeft = 9;
			
			// aapt resource value: 10
			public const int CardView_contentPaddingRight = 10;
			
			// aapt resource value: 11
			public const int CardView_contentPaddingTop = 11;
			
			public static int[] RecyclerView = new int[] {
					16842948,
					16842993,
					2130771968,
					2130771969,
					2130771970,
					2130771971};
			
			// aapt resource value: 1
			public const int RecyclerView_android_descendantFocusability = 1;
			
			// aapt resource value: 0
			public const int RecyclerView_android_orientation = 0;
			
			// aapt resource value: 2
			public const int RecyclerView_layoutManager = 2;
			
			// aapt resource value: 4
			public const int RecyclerView_reverseLayout = 4;
			
			// aapt resource value: 3
			public const int RecyclerView_spanCount = 3;
			
			// aapt resource value: 5
			public const int RecyclerView_stackFromEnd = 5;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
